/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './logout.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
var renderType_LogoutCompnent_Host:import0.RenderComponentType = (null as any);
class _View_LogoutCompnent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LogoutCompnent_0_4:import3.LogoutCompnent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LogoutCompnent_Host0,renderType_LogoutCompnent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-logout',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LogoutCompnent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LogoutCompnent_0_4 = new import3.LogoutCompnent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._LogoutCompnent_0_4,[],compView_0);
    compView_0.create(this._LogoutCompnent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LogoutCompnent) && (0 === requestNodeIndex))) { return this._LogoutCompnent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LogoutCompnent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LogoutCompnent_Host === (null as any))) { (renderType_LogoutCompnent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_LogoutCompnent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LogoutCompnentNgFactory:import11.ComponentFactory<import3.LogoutCompnent> = new import11.ComponentFactory<import3.LogoutCompnent>('app-logout',viewFactory_LogoutCompnent_Host0,import3.LogoutCompnent);
const styles_LogoutCompnent:any[] = [];
var renderType_LogoutCompnent:import0.RenderComponentType = (null as any);
class _View_LogoutCompnent0 extends import1.AppView<import3.LogoutCompnent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LogoutCompnent0,renderType_LogoutCompnent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n                ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','col-md-8 col-md-offset-2');
    this._text_2 = this.renderer.createText(this._el_1,'\n                    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','btn btn-danger');
    this._text_4 = this.renderer.createText(this._el_3,' Log out',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onLogout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LogoutCompnent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LogoutCompnent> {
  if ((renderType_LogoutCompnent === (null as any))) { (renderType_LogoutCompnent = viewUtils.createRenderComponentType('C:/Dev/angular2-nodejs-udemy-seed-project/01 Seed/assets/app/auth/logout.component.ts class LogoutCompnent - inline template',0,import10.ViewEncapsulation.None,styles_LogoutCompnent,{})); }
  return new _View_LogoutCompnent0(viewUtils,parentInjector,declarationEl);
}